##Numpy Array with Basics

In [2]:
import numpy as np


In [4]:
#creating array from list

arr_1d=np.array([1,2,3,4,5])
print("1d aray:",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2d aray:",arr_2d)



1d aray: [1 2 3 4 5]
2d aray: [[1 2 3]
 [4 5 6]]


##list vs numpy array



In [ ]:
py_list=[1,2,3]
print("python list multiplication",py_list*2)

np_array=np.array([1,2,3]) #element vise multiplication
print("python list multiplication",np_array*2)

python list multiplication [1, 2, 3, 1, 2, 3]
python list multiplication [2 4 6]


In [11]:
import time

# Python list operation
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("List operation time: ", time.time() - start)

# NumPy array operation
start = time.time()
np_array = np.arange(1000000) * 2
print("NumPy operation time: ", time.time() - start)


List operation time:  0.23658180236816406
NumPy operation time:  0.03341269493103027


creating array from scratch

In [17]:
zeros=np.zeros((3,4))
print("zeros array:\n",zeros)


ones=np.ones((2,3))
print("ones array:\n",ones)

full=np.full((3,2),7)
print("full array:\n",full)

random=np.random.random((2,3))
print("random array:\n",random)

sequence=np.arange(0,11,2)
print("sequence array:\n",sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]
 [7 7]]
random array:
 [[0.08374674 0.98473292 0.57144579]
 [0.33101884 0.56561408 0.14023865]]
sequence array:
 [ 0  2  4  6  8 10]


vector,matrix,tensor

In [18]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)


tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array properties

In [19]:
arr=np.array([[1,2,3],
             [4,5,6]])

print("size",arr.size)
print("dimension",arr.ndim)
print("shape",arr.shape)
print("Dtype",arr.dtype)

size 6
dimension 2
shape (2, 3)
Dtype int64


Array reshaping

In [34]:
arr=np.arange(12)
print("original array ",arr)

reshaped=arr.reshape([3,4])
print("reshaped array ",reshaped)

flattened=reshaped.flatten()
print("flattened array ",flattened)

#ravel (returns a view instead of copy)
raveled=reshaped.ravel()
print("raveled array ",raveled)

#Transpose
transpose=reshaped.T
print("transposed array ",transpose)



original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
